name: roocs_utils
channels:
 - conda-forge
 - defaults
dependencies:
 - numpy>=1.16
 - xarray>=0.15
 - dask>=2.6
 - cftime
 - python-dateutil>=2.8.1
 - cf_xarray>=0.3.1 # Note that conda-forge package is cf_xarray (!= cf-xarray)
 - netCDF4>=1.4
 - oyaml>=0.9
 - pyyaml>=5.3
